version: '3.8'

services:
  mysql:
    image: mysql:5.7.16
    container_name: 'mysql'
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Root-2022
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=Laravel-2022
      - TZ=Asia/Tokyo
  php:
    build: ./docker/php/
    container_name: 'php'
    tty: true
    stdin_open: true
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - "./umarche:/home/laravel/umarche"
    depends_on:
      - mysql
    extra_hosts:
      - host.docker.internal:host-gateway
  httpd:
    build: ./docker/httpd/
    container_name: 'httpd'
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 8080:80
    volumes:
      - "./umarche:/home/laravel/umarche"
    depends_on:
      - php
      - mysql
